sudo: required
language: node_js
node_js:
  - '8'

addons:
  chrome: stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then grunt ci; else grunt ci-pull; fi'

env:
  global:
  - secure: TtJA9tFI8v5oZAsByeiSLyYkggGuSn+NUyHKNBIvzwxAVF+EOZeMJq7AfX0k5TwlQpP+k/7IrE98AxNA3bR7dEyKj33sX7Pj4YSxZaCO+YbeweGyzHSFuT98T0H+xGEA98dhZt2/5ekpgNuanSZfcIo8Rwzx1+Uhbrs1wggslMP3XNrJyHSEk63uMDsSU5e+rCzFxftCeACz8FzQRse914Wmeg5XJVhdfA0X8D0SiPyGKHOL/+zfP0DDVPpd7wihe0z5QUI3IpDhAAI15s2QkWGTKewMzDZ39OF7gxQh9I+xwO7LxzzlaLnlC1Zzdz3Q2MAEvQeFtBiFNziX7DbzLZo83agAnzQFDcyA7XoINeGdKFdOC4hgyPW8x/bNy1FnXnYJ/PwunraSNV168cWQQ6N/j5UFVXPgXAEolTz14ZjUTsolJ+MOuMA95aKRZtwPNV6qdEko78SOUixSLzSGwB9tTNCCTpuk3KqiS9SHjxg39UDAcYJ1TO+yxeV6xT2MxC11GqyEfO/wYUJAM6VPR1ca4vCqzNuN3MEanN0qliEFEwNp8B9h/ODPMA/NNi52dSMFUPb1D9xpOybaAzjVq+wGoCv7T6AkolgcIR9/+3qd0l4NY7btrkIAdbK2WvTaX24KSpHIJo5nFRgKaDYSkcgvq1mTQtLLamqfWM8P52E=
  - secure: XGKWY/KTIzthSDiECMcDTm0+J0+hVQ4xeDGsb7BDmrGZXP7EbBKvf8jk3mmBz0IFUk6GyPWDjD4kQzhpRyB9AH1bQ48yFQHgsUaaEebVquHnzcmnoFy2P48VCxolCUlcNjqW4MLMxVMa+J5Yr7lu4JMC8m7PZCh5uG+UhG36WGWzXPvtAmEW530B5BK9NGoZrNOASKiK45CO0HivOmheyEWGfgphwtlBDKHXA2TV2Kqo1MZKlpaGaE0yb+iPTaIPq2hCrO/tui95vKhf2f1V0pHHwq8hG1bePnhp3oAQrLtKLsI1jOyX+oKaCSdmzpN9y8W+W5OalQTDhfdeTCKxVj514+jPmnErMEtgq+yRci8y5cub7oQQFYCRhe3/FnyJ9D8G6QwUJ88NkJ6Mlk73kmDhOq2ZvaqJbatMo7lr/BJWQ7QshDC9gOp9QXNxfg6dPsbo4+uLXTrEC4ak8TLivHMzDGOZwMWiHvn7JwmPauKR/hjDfeakqUXNjPIezZ31e9hen8XGaZ77kYkFlsGEuvmTs9KhtYKUNxmva6JjRuYOasntBjgdTq6QrlnkIBfZ0aYhnqfnvFRatuXICUzAqj9e5ywk5oN8jItznRhg/MRyMs9qOesqM2k5NVuPKklCKgfL37NvQpxvVWuRk9PGGelGGB4NI89bJE4ZyLeYayU=
